stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - npm install
    - npm run build

unit-test-job:
  stage: test
  script:
    - npm test

lint-test-job:
  stage: test
  script:
    - npm run lint

deploy-job:
  stage: deploy
  environment: production
  script:
    - ssh user@your-server 'cd /path/to/project && git pull origin main && npm install && npm run start'
  only:
    - main
