stages:
  - install
  - test

install_dependencies:
  stage: install
  image: node:20
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

run_tests:
  stage: test
  image: node:20
  script:
    - npm test
